services:
  app-test:
    build: .
    command: flutter test --coverage
    volumes:
      - .:/app

  app-analyze:
    build: .
    command: flutter analyze
    volumes:
      - .:/app

  app-format:
    build: .
    command: dart format --set-exit-if-changed .
    volumes:
      - .:/app

  app-build:
    build: .
    command: flutter build apk --debug
    volumes:
      - .:/app
